#include "constants.hpp"

#ifndef CONFIG_HEADER

#define CONFIG_HEADER

#define RESET_VELOCITY_THRESHOLD 5 * SECONDS_TO_MICROSECONDS

#define LONG_PRESS_THRESHOLD  1000
#define CLICK_PRESS_THRESHOLD  250

#endif